-- Lead gap analysis / Discrepancy Analysis
-- Retrieve non-billable calls from relevant sources
-- SET GLOBAL regexp_time_limit=1024;
select 
	c.source, c.contact_number_clean, c.called_at_utc, c.called_at_denver, c.sale_billable, c.duration,
    case
        when lower(s.summary) regexp '((tech|employee|truck|advert)\w*\b) (\w+ )*in (\w+ )*(((zip|area|region|city)((.)*code)?|address|state|neighborhood)(\w)*\b)|caller (\w+ )*refer\w*\b' then 'Referral'
        when lower(s.summary) regexp 'caller (\w+ )*(return(\w)* call|call(\w)* back)' then 'RepeatCaller'
        when lower(s.summary) regexp 'spanish( call| speaking)?|call is in spanish' then 'Spanish'
        when lower(s.summary) regexp '(they|fox|we|he|she|them|him|her) (not|(is|are|do|ca)(.)*n(.)*t(.)?) (((offer|provid|treat|servic|cover|do|spray)(\w)*\b) )?(((plan|servic|treat|((estimat|inspect|((quote|quoet|queot|qeuot|equot|qutoe|qtuoe|tquoe|qoute|oqute|quteo|uqote|qoteu|qotue|uoteq|uotqe|uoqte|quot|quto|qtuo|tquo|qout|oqut|uqot|qotu|uotq|uoqt|qute|quet|qeut|equt|qtue|tque|uqte|qteu|uteq|utqe|quoe|queo|qeuo|equo|qoue|oque|uqoe|qoeu|uoeq|uoqe|cuote|cuoet|cueot|ceuot|ecuot|cutoe|ctuoe|tcuoe|coute|ocute|cuteo|ucote|coteu|cotue|uotec|uotce|uocte|cuot|cuto|ctuo|tcuo|cout|ocut|ucot|cotu|uotc|uoct|cute|cuet|ceut|ecut|ctue|tcue|ucte|cteu|utec|utce|cuoe|cueo|ceuo|ecuo|coue|ocue|ucoe|coeu|uoec|uoce)(\w)*))(\w)*\b)|app(.)*t|estimat|take care of ?)(\w)*\b) )?(\w+ ){0,5}(((zip|area|region|city)((.)*code)?|address|state|neighborhood)(\w)*\b)|(wrong|incorrect|improper|outside( \w+){0,3}\b|not in\w*( of)?\b) (((plan|servic|treat|((estimat|inspect|((quote|quoet|queot|qeuot|equot|qutoe|qtuoe|tquoe|qoute|oqute|quteo|uqote|qoteu|qotue|uoteq|uotqe|uoqte|quot|quto|qtuo|tquo|qout|oqut|uqot|qotu|uotq|uoqt|qute|quet|qeut|equt|qtue|tque|uqte|qteu|uteq|utqe|quoe|queo|qeuo|equo|qoue|oque|uqoe|qoeu|uoeq|uoqe|cuote|cuoet|cueot|ceuot|ecuot|cutoe|ctuoe|tcuoe|coute|ocute|cuteo|ucote|coteu|cotue|uotec|uotce|uocte|cuot|cuto|ctuo|tcuo|cout|ocut|ucot|cotu|uotc|uoct|cute|cuet|ceut|ecut|ctue|tcue|ucte|cteu|utec|utce|cuoe|cueo|ceuo|ecuo|coue|ocue|ucoe|coeu|uoec|uoce)(\w)*))(\w)*\b)|app(.)*t|estimat|take care of ?)(\w)*\b) )?(((zip|area|region|city)((.)*code)?|address|state|neighborhood)(\w)*\b)|(they|fox|we|he|she|them|him|her) (not|(is|are|do|ca)(.)*n(.)*t(.)?) (\w+ ){0,3}(((zip|area|region|city)((.)*code)?|address|state|neighborhood)(\w)*\b)' then 'WrongArea'
        when lower(s.summary) regexp '(((honey|bumble)(.)*bee|snake|gopher|ground(.)*hog|squirrel|wildlife)(\w)*\b)|no.kill (\w+ ){0,3}for|(they|fox|we|he|she|them|him|her) (\w+ )* (not|(is|are|do|ca)(.)*n(.)*t(.)?) ((offer|provid|treat|servic|cover|do|spray)(\w)*\b)( (\w+ ){0,3}((plan|servic|treat|((estimat|inspect|((quote|quoet|queot|qeuot|equot|qutoe|qtuoe|tquoe|qoute|oqute|quteo|uqote|qoteu|qotue|uoteq|uotqe|uoqte|quot|quto|qtuo|tquo|qout|oqut|uqot|qotu|uotq|uoqt|qute|quet|qeut|equt|qtue|tque|uqte|qteu|uteq|utqe|quoe|queo|qeuo|equo|qoue|oque|uqoe|qoeu|uoeq|uoqe|cuote|cuoet|cueot|ceuot|ecuot|cutoe|ctuoe|tcuoe|coute|ocute|cuteo|ucote|coteu|cotue|uotec|uotce|uocte|cuot|cuto|ctuo|tcuo|cout|ocut|ucot|cotu|uotc|uoct|cute|cuet|ceut|ecut|ctue|tcue|ucte|cteu|utec|utce|cuoe|cueo|ceuo|ecuo|coue|ocue|ucoe|coeu|uoec|uoce)(\w)*))(\w)*\b)|app(.)*t|estimat|take care of ?)(\w)*\b))?|((plan|servic|treat|((estimat|inspect|((quote|quoet|queot|qeuot|equot|qutoe|qtuoe|tquoe|qoute|oqute|quteo|uqote|qoteu|qotue|uoteq|uotqe|uoqte|quot|quto|qtuo|tquo|qout|oqut|uqot|qotu|uotq|uoqt|qute|quet|qeut|equt|qtue|tque|uqte|qteu|uteq|utqe|quoe|queo|qeuo|equo|qoue|oque|uqoe|qoeu|uoeq|uoqe|cuote|cuoet|cueot|ceuot|ecuot|cutoe|ctuoe|tcuoe|coute|ocute|cuteo|ucote|coteu|cotue|uotec|uotce|uocte|cuot|cuto|ctuo|tcuo|cout|ocut|ucot|cotu|uotc|uoct|cute|cuet|ceut|ecut|ctue|tcue|ucte|cteu|utec|utce|cuoe|cueo|ceuo|ecuo|coue|ocue|ucoe|coeu|uoec|uoce)(\w)*))(\w)*\b)|app(.)*t|estimat|take care of ?)(\w)*\b) (not|(is|are|do|ca)(.)*n(.)*t(.)?) ((offer|provid|treat|servic|cover|do|spray)(\w)*\b)' then 'ServiceNotOffered'
        when lower(s.summary) regexp '(single|attached) ((unit|complex|building|condo(\w)*|apartment)|apartment(.)?(unit|complex|building|condo(\w)*|apartment))( in a complex)?|((unit|complex|building|condo(\w)*|apartment)|apartment(.)?(unit|complex|building|condo(\w)*|apartment)) caller|(discuss|talk|ask) (\w+ ){0,5}(((land|propert|ho(m|us)e|((unit|complex|building|condo(\w)*|apartment)|apartment(.)?(unit|complex|building|condo(\w)*|apartment))) ?((own|manag|admin)(\w)*\b))|((own|manag|admin)(\w)*\b))|(((unit|complex|building|condo(\w)*|apartment)|apartment(.)?(unit|complex|building|condo(\w)*|apartment)) )?(((land|propert|ho(m|us)e|((unit|complex|building|condo(\w)*|apartment)|apartment(.)?(unit|complex|building|condo(\w)*|apartment))) ?((own|manag|admin)(\w)*\b))|((own|manag|admin)(\w)*\b)) (permission|approval)|((reach(\w)* out to|talk(\w)* to|speak(\w)*( ?(to|with))?|get in touch with|call|permission from|contact|coordinat|check with)(\w)*\b) (((land|propert|ho(m|us)e|((unit|complex|building|condo(\w)*|apartment)|apartment(.)?(unit|complex|building|condo(\w)*|apartment))) ?((own|manag|admin)(\w)*\b))|((own|manag|admin)(\w)*\b))|(not|(is|are|do|ca)(.)*n(.)*t(.)?) ((offer|provid|treat|servic|cover|do|spray)(\w)*\b) (\w+ ){0,3}((unit|complex|building|condo(\w)*|apartment)|apartment(.)?(unit|complex|building|condo(\w)*|apartment))|(need|ask|get)(\w)* (\w+ )*(((land|propert|ho(m|us)e|((unit|complex|building|condo(\w)*|apartment)|apartment(.)?(unit|complex|building|condo(\w)*|apartment))) ?((own|manag|admin)(\w)*\b))|((own|manag|admin)(\w)*\b))( permission)?' then 'Renter'
        when lower(s.summary) regexp '((caller|this|we|i)? ?(is |am )a )?current (client|clietn|cliten|cltien|ctlien|tclien|clinet|clniet|cnliet|ncliet|cleint|celint|eclint|clinte|cilent|iclent|clenti|clenit|lcient|cientl|cienlt|cielnt|licent|liecnt|lienct|lientc|clien|cline|clnie|cnlie|nclie|clein|celin|eclin|cilen|iclen|cleni|lcien|cienl|cieln|licen|liecn|lienc|cliet|clite|cltie|ctlie|tclie|cleit|celit|eclit|cilet|iclet|cleti|lciet|cietl|cielt|licet|liect|lietc|clint|clitn|cltin|ctlin|tclin|clnit|cnlit|nclit|cilnt|iclnt|clnti|lcint|cintl|cinlt|licnt|linct|lintc|clent|cletn|clten|ctlen|tclen|clnet|cnlet|nclet|celnt|eclnt|clnte|lcent|centl|cenlt|lecnt|lenct|lentc|cient|cietn|citen|ctien|tcien|cinet|cniet|nciet|ceint|ecint|cinte|icent|centi|cenit|iecnt|ienct|ientc|customer|customre|custorme|custrome|cusrtome|curstome|crustome|rcustome|custoemr|custeomr|cusetomr|cuestomr|ceustomr|ecustomr|custmoer|cusmtoer|cumstoer|cmustoer|mcustoer|custoerm|cutsomer|ctusomer|tcusomer|cusomert|cusometr|cusomter|cusotmer|ucstomer|usctomer|ustcomer|ustocmer|ustomcer|ustomecr|ustomerc|custome|custoem|custeom|cusetom|cuestom|ceustom|ecustom|custmoe|cusmtoe|cumstoe|cmustoe|mcustoe|cusotme|cuostme|coustme|ocustme|custmeo|cutsome|ctusome|tcusome|cusomet|cusomte|csutome|scutome|cutomes|cutomse|cutosme|ucstome|cstomeu|cstomue|cstoume|cstuome|custoner|custonre|custorne|custrone|cusrtone|curstone|crustone|rcustone|custoenr|custeonr|cusetonr|cuestonr|ceustonr|ecustonr|custnoer|cusntoer|cunstoer|cnustoer|ncustoer|custoern|cutsoner|ctusoner|tcusoner|cusonert|cusonetr|cusonter|cusotner|ucstoner|usctoner|ustconer|ustocner|ustoncer|ustonecr|ustonerc|custone|custoen|custeon|cuseton|cueston|ceuston|ecuston|custnoe|cusntoe|cunstoe|cnustoe|ncustoe|cusotne|cuostne|coustne|ocustne|custneo|cutsone|ctusone|tcusone|cusonet|cusonte|csutone|scutone|cutones|cutonse|cutosne|ucstone|cstoneu|cstonue|cstoune|cstuone|cus)|previously billed' then 'Current Customer'
        when lower(s.summary) regexp 'no one (\w+ ){0,3}after (\w+ )*(\d+|\w+) (second|minute)|on hold (\w+ ){0,5}|(caller )?interact(\w)* (\w+ ){0,3}ivr|caller (h.ng(s|ed|ing)?.*up) before|(hold|wait) (music|time)|call (rings|rang) (multiple|many|several|a lot( of)?|a bunch( of)?)|((h.ng(s|ed|ing)?.*up) (after|immediately)|(caller )?(rings|rang) (multiple|many|several|a lot( of)?|a bunch( of)?) time(s)?)|code red|(h.ng(s|ed|ing)?.*up) without (leaving )?(a |any )?message|call end(\w)* after|(h.ng(s|ed|ing)?.*up) before (anyone|someone) (can|could) answer|(h.ng(s|ed|ing)?.*up) without interact(\w)* (\w+ )*ivr|(answering )?machine|conversation (\w+ )*(record(\w)* message|automated)' then 'MissedCall'
        when lower(s.summary) regexp 'call (\w+ ){0,5}disconnect\w*\b|no one speaks (\w+ )*(line|end)|with a live agent|(h.ng(s|ed|ing)?.*up) on (\w+ )*(rep|sale.*(man|woman|person|guy)|(they|fox|we|he|she|them|him|her))(\w)*|(call|speak)(\w)* (h.ng(s|ed|ing)?.*up) (\w+ )*call (\w+ )*answer\w*\b|(end|(h.ng(s|ed|ing)?.*up))(\w)* (\w+ ){0,3}immediat(\w)*|dead air|no audio|(unresponsive caller|caller (is |was )?unresponsive)|caller (h.ng(s|ed|ing)?.*up) up (\w+ )*(rep|sale.*(man|woman|person|guy)|(they|fox|we|he|she|them|him|her))(\w)* answer\w*\b( the call)?' then 'Hang Up'
        when lower(s.summary) regexp '\$.?\d+.*(\$.?\d+)?' then 'Maybe Billable?'
        when lower(s.summary) regexp 'problem.*request(\w)* (\w+ )call back' then 'Maybe Billable? 1'
		when lower(s.summary) regexp '(look(\w)* ?|need|ask(\w)* ?|want|request)(\w)*\b pest control ((plan|servic|treat|((estimat|inspect|((quote|quoet|queot|qeuot|equot|qutoe|qtuoe|tquoe|qoute|oqute|quteo|uqote|qoteu|qotue|uoteq|uotqe|uoqte|quot|quto|qtuo|tquo|qout|oqut|uqot|qotu|uotq|uoqt|qute|quet|qeut|equt|qtue|tque|uqte|qteu|uteq|utqe|quoe|queo|qeuo|equo|qoue|oque|uqoe|qoeu|uoeq|uoqe|cuote|cuoet|cueot|ceuot|ecuot|cutoe|ctuoe|tcuoe|coute|ocute|cuteo|ucote|coteu|cotue|uotec|uotce|uocte|cuot|cuto|ctuo|tcuo|cout|ocut|ucot|cotu|uotc|uoct|cute|cuet|ceut|ecut|ctue|tcue|ucte|cteu|utec|utce|cuoe|cueo|ceuo|ecuo|coue|ocue|ucoe|coeu|uoec|uoce)(\w)*))(\w)*\b)''app(.)*t|estimat|take care of ?)(\w)*\b)(\w)* for \w*\b' then 'Maybe Billable? 2'
        when lower(s.summary) regexp 'same(.)?day (\w+ ){0,5}((plan|servic|treat|((estimat|inspect|((quote|quoet|queot|qeuot|equot|qutoe|qtuoe|tquoe|qoute|oqute|quteo|uqote|qoteu|qotue|uoteq|uotqe|uoqte|quot|quto|qtuo|tquo|qout|oqut|uqot|qotu|uotq|uoqt|qute|quet|qeut|equt|qtue|tque|uqte|qteu|uteq|utqe|quoe|queo|qeuo|equo|qoue|oque|uqoe|qoeu|uoeq|uoqe|cuote|cuoet|cueot|ceuot|ecuot|cutoe|ctuoe|tcuoe|coute|ocute|cuteo|ucote|coteu|cotue|uotec|uotce|uocte|cuot|cuto|ctuo|tcuo|cout|ocut|ucot|cotu|uotc|uoct|cute|cuet|ceut|ecut|ctue|tcue|ucte|cteu|utec|utce|cuoe|cueo|ceuo|ecuo|coue|ocue|ucoe|coeu|uoec|uoce)(\w)*))(\w)*\b)|app(.)*t|estimat|take care of ?)(\w)*\b)' then 'Maybe Billable? 3'
        when lower(s.summary) regexp '(book|schedule|set up|get) (\w+ ){0,3}((plan|servic|treat|((estimat|inspect|((quote|quoet|queot|qeuot|equot|qutoe|qtuoe|tquoe|qoute|oqute|quteo|uqote|qoteu|qotue|uoteq|uotqe|uoqte|quot|quto|qtuo|tquo|qout|oqut|uqot|qotu|uotq|uoqt|qute|quet|qeut|equt|qtue|tque|uqte|qteu|uteq|utqe|quoe|queo|qeuo|equo|qoue|oque|uqoe|qoeu|uoeq|uoqe|cuote|cuoet|cueot|ceuot|ecuot|cutoe|ctuoe|tcuoe|coute|ocute|cuteo|ucote|coteu|cotue|uotec|uotce|uocte|cuot|cuto|ctuo|tcuo|cout|ocut|ucot|cotu|uotc|uoct|cute|cuet|ceut|ecut|ctue|tcue|ucte|cteu|utec|utce|cuoe|cueo|ceuo|ecuo|coue|ocue|ucoe|coeu|uoec|uoce)(\w)*))(\w)*\b)|app(.)*t|estimat|take care of ?)(\w)*\b)'then 'Maybe Billable? 4'
        when lower(s.summary) regexp '(look(\w)* ?|need|ask(\w)* ?|want|request)(\w)*\b (\w+ )*free ((estimat|inspect|((quote|quoet|queot|qeuot|equot|qutoe|qtuoe|tquoe|qoute|oqute|quteo|uqote|qoteu|qotue|uoteq|uotqe|uoqte|quot|quto|qtuo|tquo|qout|oqut|uqot|qotu|uotq|uoqt|qute|quet|qeut|equt|qtue|tque|uqte|qteu|uteq|utqe|quoe|queo|qeuo|equo|qoue|oque|uqoe|qoeu|uoeq|uoqe|cuote|cuoet|cueot|ceuot|ecuot|cutoe|ctuoe|tcuoe|coute|ocute|cuteo|ucote|coteu|cotue|uotec|uotce|uocte|cuot|cuto|ctuo|tcuo|cout|ocut|ucot|cotu|uotc|uoct|cute|cuet|ceut|ecut|ctue|tcue|ucte|cteu|utec|utce|cuoe|cueo|ceuo|ecuo|coue|ocue|ucoe|coeu|uoec|uoce)(\w)*))(\w)*\b)' then 'Maybe Billable? 5'
        when lower(s.summary) regexp '(rep|sale.*(man|woman|person|guy)|(they|fox|we|he|she|them|him|her))(\w)* (((((say|said|stat|intimat|allud)(\w)*\b) (they|fox|we|he|she|them|him|her) ((could|can|will|would|do(\w)*)\b) ((offer|provid|treat|servic|cover|do|spray)(\w)*\b)|rec.*om.*end|assur(\w)* (\w+ ){0,5}(they|fox|we|he|she|them|him|her))(\w)*\b)|((say|said|stat|intimat|allud)(\w)*\b)) (\w+ )*((plan|servic|treat|((estimat|inspect|((quote|quoet|queot|qeuot|equot|qutoe|qtuoe|tquoe|qoute|oqute|quteo|uqote|qoteu|qotue|uoteq|uotqe|uoqte|quot|quto|qtuo|tquo|qout|oqut|uqot|qotu|uotq|uoqt|qute|quet|qeut|equt|qtue|tque|uqte|qteu|uteq|utqe|quoe|queo|qeuo|equo|qoue|oque|uqoe|qoeu|uoeq|uoqe|cuote|cuoet|cueot|ceuot|ecuot|cutoe|ctuoe|tcuoe|coute|ocute|cuteo|ucote|coteu|cotue|uotec|uotce|uocte|cuot|cuto|ctuo|tcuo|cout|ocut|ucot|cotu|uotc|uoct|cute|cuet|ceut|ecut|ctue|tcue|ucte|cteu|utec|utce|cuoe|cueo|ceuo|ecuo|coue|ocue|ucoe|coeu|uoec|uoce)(\w)*))(\w)*\b)|app(.)*t|estimat|take care of ?)(\w)*\b)'then 'Maybe Billable? 6'
        when lower(s.summary) regexp '((say|said|stat|intimat|allud)(\w)*\b) (\w+ )*((reach(\w)* out to|talk(\w)* to|speak(\w)*( ?(to|with))?|get in touch with|call|permission from|contact|coordinat|check with)(\w)*\b) (\w+ )*(they|fox|we|he|she|them|him|her) (soon|as soon as|right away|immediate(\w)*)'then 'Maybe Billable? 7'
        when lower(s.summary) regexp '(look(\w)* ?|need|ask(\w)* ?|want|request)(\w)*\b pest control (((plan|servic|treat|((estimat|inspect|((quote|quoet|queot|qeuot|equot|qutoe|qtuoe|tquoe|qoute|oqute|quteo|uqote|qoteu|qotue|uoteq|uotqe|uoqte|quot|quto|qtuo|tquo|qout|oqut|uqot|qotu|uotq|uoqt|qute|quet|qeut|equt|qtue|tque|uqte|qteu|uteq|utqe|quoe|queo|qeuo|equo|qoue|oque|uqoe|qoeu|uoeq|uoqe|cuote|cuoet|cueot|ceuot|ecuot|cutoe|ctuoe|tcuoe|coute|ocute|cuteo|ucote|coteu|cotue|uotec|uotce|uocte|cuot|cuto|ctuo|tcuo|cout|ocut|ucot|cotu|uotc|uoct|cute|cuet|ceut|ecut|ctue|tcue|ucte|cteu|utec|utce|cuoe|cueo|ceuo|ecuo|coue|ocue|ucoe|coeu|uoec|uoce)(\w)*))(\w)*\b)|app(.)*t|estimat|take care of ?)(\w)*\b)|company)'then 'Maybe Billable? 8'
        when lower(s.summary) regexp '(look(\w)* ?|need|ask(\w)* ?|want|request)(\w)*\b (\w+ )*a ((quote|quoet|queot|qeuot|equot|qutoe|qtuoe|tquoe|qoute|oqute|quteo|uqote|qoteu|qotue|uoteq|uotqe|uoqte|quot|quto|qtuo|tquo|qout|oqut|uqot|qotu|uotq|uoqt|qute|quet|qeut|equt|qtue|tque|uqte|qteu|uteq|utqe|quoe|queo|qeuo|equo|qoue|oque|uqoe|qoeu|uoeq|uoqe|cuote|cuoet|cueot|ceuot|ecuot|cutoe|ctuoe|tcuoe|coute|ocute|cuteo|ucote|coteu|cotue|uotec|uotce|uocte|cuot|cuto|ctuo|tcuo|cout|ocut|ucot|cotu|uotc|uoct|cute|cuet|ceut|ecut|ctue|tcue|ucte|cteu|utec|utce|cuoe|cueo|ceuo|ecuo|coue|ocue|ucoe|coeu|uoec|uoce)(\w)*)'then 'Maybe Billable? 9'
        when lower(s.summary) regexp '(rep|sale.*(man|woman|person|guy)|(they|fox|we|he|she|them|him|her))(\w)* ((say|said|stat|intimat|allud)(\w)*\b) (\w+ )*((plan|servic|treat|((estimat|inspect|((quote|quoet|queot|qeuot|equot|qutoe|qtuoe|tquoe|qoute|oqute|quteo|uqote|qoteu|qotue|uoteq|uotqe|uoqte|quot|quto|qtuo|tquo|qout|oqut|uqot|qotu|uotq|uoqt|qute|quet|qeut|equt|qtue|tque|uqte|qteu|uteq|utqe|quoe|queo|qeuo|equo|qoue|oque|uqoe|qoeu|uoeq|uoqe|cuote|cuoet|cueot|ceuot|ecuot|cutoe|ctuoe|tcuoe|coute|ocute|cuteo|ucote|coteu|cotue|uotec|uotce|uocte|cuot|cuto|ctuo|tcuo|cout|ocut|ucot|cotu|uotc|uoct|cute|cuet|ceut|ecut|ctue|tcue|ucte|cteu|utec|utce|cuoe|cueo|ceuo|ecuo|coue|ocue|ucoe|coeu|uoec|uoce)(\w)*))(\w)*\b)|app(.)*t|estimat|take care of ?)(\w)*\b)'then 'Maybe Billable? 10'
        when lower(s.summary) regexp '((plan|servic|treat|((estimat|inspect|((quote|quoet|queot|qeuot|equot|qutoe|qtuoe|tquoe|qoute|oqute|quteo|uqote|qoteu|qotue|uoteq|uotqe|uoqte|quot|quto|qtuo|tquo|qout|oqut|uqot|qotu|uotq|uoqt|qute|quet|qeut|equt|qtue|tque|uqte|qteu|uteq|utqe|quoe|queo|qeuo|equo|qoue|oque|uqoe|qoeu|uoeq|uoqe|cuote|cuoet|cueot|ceuot|ecuot|cutoe|ctuoe|tcuoe|coute|ocute|cuteo|ucote|coteu|cotue|uotec|uotce|uocte|cuot|cuto|ctuo|tcuo|cout|ocut|ucot|cotu|uotc|uoct|cute|cuet|ceut|ecut|ctue|tcue|ucte|cteu|utec|utce|cuoe|cueo|ceuo|ecuo|coue|ocue|ucoe|coeu|uoec|uoce)(\w)*))(\w)*\b)|app(.)*t|estimat|take care of ?)(\w)*\b) (was|is|were|are) (schedule|set up|set)'then 'Maybe Billable? 11'
        when lower(s.summary) regexp '(rep|sale.*(man|woman|person|guy)|(they|fox|we|he|she|them|him|her))(\w)* ((((say|said|stat|intimat|allud)(\w)*\b) (they|fox|we|he|she|them|him|her) ((could|can|will|would|do(\w)*)\b) ((offer|provid|treat|servic|cover|do|spray)(\w)*\b)|rec.*om.*end|assur(\w)* (\w+ ){0,5}(they|fox|we|he|she|them|him|her))(\w)*\b) (their|the|fox.*(\w)*|the fox|our) (\w+ ){0,5}((plan|servic|treat|((estimat|inspect|((quote|quoet|queot|qeuot|equot|qutoe|qtuoe|tquoe|qoute|oqute|quteo|uqote|qoteu|qotue|uoteq|uotqe|uoqte|quot|quto|qtuo|tquo|qout|oqut|uqot|qotu|uotq|uoqt|qute|quet|qeut|equt|qtue|tque|uqte|qteu|uteq|utqe|quoe|queo|qeuo|equo|qoue|oque|uqoe|qoeu|uoeq|uoqe|cuote|cuoet|cueot|ceuot|ecuot|cutoe|ctuoe|tcuoe|coute|ocute|cuteo|ucote|coteu|cotue|uotec|uotce|uocte|cuot|cuto|ctuo|tcuo|cout|ocut|ucot|cotu|uotc|uoct|cute|cuet|ceut|ecut|ctue|tcue|ucte|cteu|utec|utce|cuoe|cueo|ceuo|ecuo|coue|ocue|ucoe|coeu|uoec|uoce)(\w)*))(\w)*\b)|app(.)*t|estimat|take care of ?)(\w)*\b)'then 'Maybe Billable? 12'
        when lower(s.summary) regexp '((rep|sale.*(man|woman|person|guy)|(they|fox|we|he|she|them|him|her))(\w)*|caller) (((say|said|stat|intimat|allud)(\w)*\b) )?(they|fox|we|he|she|them|him|her) (will|would|should|shall) (\w+ ){0,3}call (\w+ ){0,3}back'then 'Maybe Billable? 13'
        when lower(s.summary) regexp '(rep|sale.*(man|woman|person|guy)|(they|fox|we|he|she|them|him|her))(\w)* ((((say|said|stat|intimat|allud)(\w)*\b) (they|fox|we|he|she|them|him|her) ((could|can|will|would|do(\w)*)\b) ((offer|provid|treat|servic|cover|do|spray)(\w)*\b)|rec.*om.*end|assur(\w)* (\w+ ){0,5}(they|fox|we|he|she|them|him|her))(\w)*\b) (\w+ ){0,3}(their|the|fox.*(\w)*|the fox|our) ((plan|servic|treat|((estimat|inspect|((quote|quoet|queot|qeuot|equot|qutoe|qtuoe|tquoe|qoute|oqute|quteo|uqote|qoteu|qotue|uoteq|uotqe|uoqte|quot|quto|qtuo|tquo|qout|oqut|uqot|qotu|uotq|uoqt|qute|quet|qeut|equt|qtue|tque|uqte|qteu|uteq|utqe|quoe|queo|qeuo|equo|qoue|oque|uqoe|qoeu|uoeq|uoqe|cuote|cuoet|cueot|ceuot|ecuot|cutoe|ctuoe|tcuoe|coute|ocute|cuteo|ucote|coteu|cotue|uotec|uotce|uocte|cuot|cuto|ctuo|tcuo|cout|ocut|ucot|cotu|uotc|uoct|cute|cuet|ceut|ecut|ctue|tcue|ucte|cteu|utec|utce|cuoe|cueo|ceuo|ecuo|coue|ocue|ucoe|coeu|uoec|uoce)(\w)*))(\w)*\b)|app(.)*t|estimat|take care of ?)(\w)*\b)'then 'Maybe Billable? 14'
        when lower(s.summary) regexp 'conversation.*(inquir|service agreement|suspect)(\w)* (\w+ )*((\bant|bug|bee|beetle|"box.*elder|"carpenter.*(ant|bee)|centipede|"(c.*k)?.*ro.*ch|cricket|earwig|fle|fly|fli|"\b(g)?nat\b|hornet|insect|"lady.{0,5}bug|mice|millipede|mole|"mosqu(\w)*o|moth|mouse|"((nest|gnaw)(\w)*)|"\bpest.*(control)?|"\brat|rodent|"scorp(\w)*n|"((problem|remov|re(\w)*c(\w)*ur(\w)* servic|treat|spray|bomb|(pest|yard|home) control|visit|servi(c|d)|exterminat|infest|inspect|fumiga|(quote|quoet|queot|qeuot|equot|qutoe|qtuoe|tquoe|qoute|oqute|quteo|uqote|qoteu|qotue|uoteq|uotqe|uoqte|quot|quto|qtuo|tquo|qout|oqut|uqot|qotu|uotq|uoqt|qute|quet|qeut|equt|qtue|tque|uqte|qteu|uteq|utqe|quoe|queo|qeuo|equo|qoue|oque|uqoe|qoeu|uoeq|uoqe|cuote|cuoet|cueot|ceuot|ecuot|cutoe|ctuoe|tcuoe|coute|ocute|cuteo|ucote|coteu|cotue|uotec|uotce|uocte|cuot|cuto|ctuo|tcuo|cout|ocut|ucot|cotu|uotc|uoct|cute|cuet|ceut|ecut|ctue|tcue|ucte|cteu|utec|utce|cuoe|cueo|ceuo|ecuo|coue|ocue|ucoe|coeu|uoec|uoce))(\w)*) request|request ((problem|remov|re(\w)*c(\w)*ur(\w)* servic|treat|spray|bomb|(pest|yard|home) control|visit|servi(c|d)|exterminat|infest|inspect|fumiga|(quote|quoet|queot|qeuot|equot|qutoe|qtuoe|tquoe|qoute|oqute|quteo|uqote|qoteu|qotue|uoteq|uotqe|uoqte|quot|quto|qtuo|tquo|qout|oqut|uqot|qotu|uotq|uoqt|qute|quet|qeut|equt|qtue|tque|uqte|qteu|uteq|utqe|quoe|queo|qeuo|equo|qoue|oque|uqoe|qoeu|uoeq|uoqe|cuote|cuoet|cueot|ceuot|ecuot|cutoe|ctuoe|tcuoe|coute|ocute|cuteo|ucote|coteu|cotue|uotec|uotce|uocte|cuot|cuto|ctuo|tcuo|cout|ocut|ucot|cotu|uotc|uoct|cute|cuet|ceut|ecut|ctue|tcue|ucte|cteu|utec|utce|cuoe|cueo|ceuo|ecuo|coue|ocue|ucoe|coeu|uoec|uoce))(\w)*)|"silver.*fish|spider|spray|stink.*bug|termite|\btic|wasp|yello.*jacket.*|((problem|remov|re(\w)*c(\w)*ur(\w)* servic|treat|spray|bomb|(pest|yard|home) control|visit|servi(c|d)|exterminat|infest|inspect|fumiga|(quote|quoet|queot|qeuot|equot|qutoe|qtuoe|tquoe|qoute|oqute|quteo|uqote|qoteu|qotue|uoteq|uotqe|uoqte|quot|quto|qtuo|tquo|qout|oqut|uqot|qotu|uotq|uoqt|qute|quet|qeut|equt|qtue|tque|uqte|qteu|uteq|utqe|quoe|queo|qeuo|equo|qoue|oque|uqoe|qoeu|uoeq|uoqe|cuote|cuoet|cueot|ceuot|ecuot|cutoe|ctuoe|tcuoe|coute|ocute|cuteo|ucote|coteu|cotue|uotec|uotce|uocte|cuot|cuto|ctuo|tcuo|cout|ocut|ucot|cotu|uotc|uoct|cute|cuet|ceut|ecut|ctue|tcue|ucte|cteu|utec|utce|cuoe|cueo|ceuo|ecuo|coue|ocue|ucoe|coeu|uoec|uoce))(\w)*))(\w)*)' then 'Maybe Billable? 15'
        when lower(s.summary) regexp 'call(ed)?.*(inquir|\w*ing (\w* )*help|request|suspect|issue||quote|address|request|about|get\w\w*( rid of )?|report)(\w* )*((\bant|bug|bee|beetle|"box.*elder|"carpenter.*(ant|bee)|centipede|"(c.*k)?.*ro.*ch|cricket|earwig|fle|fly|fli|"\b(g)?nat\b|hornet|insect|"lady.{0,5}bug|mice|millipede|mole|"mosqu(\w)*o|moth|mouse|"((nest|gnaw)(\w)*)|"\bpest.*(control)?|"\brat|rodent|"scorp(\w)*n|"((problem|remov|re(\w)*c(\w)*ur(\w)* servic|treat|spray|bomb|(pest|yard|home) control|visit|servi(c|d)|exterminat|infest|inspect|fumiga|(quote|quoet|queot|qeuot|equot|qutoe|qtuoe|tquoe|qoute|oqute|quteo|uqote|qoteu|qotue|uoteq|uotqe|uoqte|quot|quto|qtuo|tquo|qout|oqut|uqot|qotu|uotq|uoqt|qute|quet|qeut|equt|qtue|tque|uqte|qteu|uteq|utqe|quoe|queo|qeuo|equo|qoue|oque|uqoe|qoeu|uoeq|uoqe|cuote|cuoet|cueot|ceuot|ecuot|cutoe|ctuoe|tcuoe|coute|ocute|cuteo|ucote|coteu|cotue|uotec|uotce|uocte|cuot|cuto|ctuo|tcuo|cout|ocut|ucot|cotu|uotc|uoct|cute|cuet|ceut|ecut|ctue|tcue|ucte|cteu|utec|utce|cuoe|cueo|ceuo|ecuo|coue|ocue|ucoe|coeu|uoec|uoce))(\w)*) request|request ((problem|remov|re(\w)*c(\w)*ur(\w)* servic|treat|spray|bomb|(pest|yard|home) control|visit|servi(c|d)|exterminat|infest|inspect|fumiga|(quote|quoet|queot|qeuot|equot|qutoe|qtuoe|tquoe|qoute|oqute|quteo|uqote|qoteu|qotue|uoteq|uotqe|uoqte|quot|quto|qtuo|tquo|qout|oqut|uqot|qotu|uotq|uoqt|qute|quet|qeut|equt|qtue|tque|uqte|qteu|uteq|utqe|quoe|queo|qeuo|equo|qoue|oque|uqoe|qoeu|uoeq|uoqe|cuote|cuoet|cueot|ceuot|ecuot|cutoe|ctuoe|tcuoe|coute|ocute|cuteo|ucote|coteu|cotue|uotec|uotce|uocte|cuot|cuto|ctuo|tcuo|cout|ocut|ucot|cotu|uotc|uoct|cute|cuet|ceut|ecut|ctue|tcue|ucte|cteu|utec|utce|cuoe|cueo|ceuo|ecuo|coue|ocue|ucoe|coeu|uoec|uoce))(\w)*)|"silver.*fish|spider|spray|stink.*bug|termite|\btic|wasp|yello.*jacket.*|((problem|remov|re(\w)*c(\w)*ur(\w)* servic|treat|spray|bomb|(pest|yard|home) control|visit|servi(c|d)|exterminat|infest|inspect|fumiga|(quote|quoet|queot|qeuot|equot|qutoe|qtuoe|tquoe|qoute|oqute|quteo|uqote|qoteu|qotue|uoteq|uotqe|uoqte|quot|quto|qtuo|tquo|qout|oqut|uqot|qotu|uotq|uoqt|qute|quet|qeut|equt|qtue|tque|uqte|qteu|uteq|utqe|quoe|queo|qeuo|equo|qoue|oque|uqoe|qoeu|uoeq|uoqe|cuote|cuoet|cueot|ceuot|ecuot|cutoe|ctuoe|tcuoe|coute|ocute|cuteo|ucote|coteu|cotue|uotec|uotce|uocte|cuot|cuto|ctuo|tcuo|cout|ocut|ucot|cotu|uotc|uoct|cute|cuet|ceut|ecut|ctue|tcue|ucte|cteu|utec|utce|cuoe|cueo|ceuo|ecuo|coue|ocue|ucoe|coeu|uoec|uoce))(\w)*))(\w)*)' then 'Maybe Billable? 16'
        else 'Unknown'
	end as classification,
    s.summary, 
    t.transcription 
from dwh_ctmdb.calls as c
left join dwh_ctmdb.transcriptions as t on t.call_id = c.call_id
left join dwh_ctmdb.call_summary as s on s.call_id = c.call_id
where 
	(source like 
		-- "%goodzer%" -- or source like
        -- "%pestnet%" -- or source like
        -- "%consumer%" -- or source like 
        "%biz%" -- or source like 
        -- "%lsa%" or source like "%local service ad%"
	)
    # Date filter
	and c.called_at_utc between date_sub(curdate(), interval 3 month) and curdate() 
	# Bilability filter
    and c.sale_billable = "non billable"